#!/usr/bin/env bash
# Configure Nginx to return "Hello World!" on root GET request

# Install Nginx
apt-get update
apt-get install -y nginx

# Create a custom Nginx configuration file
echo 'server {
    listen 80;
    server_name localhost;

    location / {
        root /var/www/html;
        index index.html;
    }

    location = / {
        return 200 "Hello World!";
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires max;
        log_not_found off;
    }
}' > /etc/nginx/sites-available/custom

# Create a symbolic link to enable the custom configuration
ln -s /etc/nginx/sites-available/custom /etc/nginx/sites-enabled/

# Remove the default Nginx configuration
rm -f /etc/nginx/sites-enabled/default

# Test Nginx configuration and restart Nginx
nginx -t && nginx -s reload
