#!/usr/bin/env bash
# Configure Nginx to return "Hello World!" on root GET request

# Install nginx
apt-get update
apt-get install -y nginx

# Configure nginx to listen on port 80
sed -i 's/80 default_server;/80;/g' /etc/nginx/sites-available/default

# Create a custom index.html file with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Restart nginx without using systemctl
/etc/init.d/nginx restart
