#!/usr/bin/env bash
# This script installs Nginx and configures a 301 redirect

# Update the package lists for upgrades and new package installations
apt-get update

# Install Nginx
apt-get install -y nginx

# Start Nginx
service nginx start

# Create a configuration file for the redirect
echo 'server {
    listen 80;
    server_name localhost;
    location = /redirect_me {
        return 301 https://www.google.com;
    }
}' | tee /etc/nginx/sites-available/redirect

# Remove the existing symbolic link if it exists
if [ -e /etc/nginx/sites-enabled/redirect ]; then
    rm /etc/nginx/sites-enabled/redirect
fi

# Create a new symbolic link
ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Remove the default configuration if it exists
if [ -e /etc/nginx/sites-enabled/default ]; then
    rm /etc/nginx/sites-enabled/default
fi

# Restart Nginx to apply the changes
/etc/init.d/nginx restart
