#!/usr/bin/env bash
# Configure Nginx to have a custom 404 page

# Install Nginx
apt-get update
apt-get install -y nginx

# Create a custom Nginx configuration file for the 404 page
echo 'server {
    listen 80;
    server_name localhost;

    location / {
        root /var/www/html;
        index index.html;
    }

    location = / {
        return 200 "Hello World!";
    }

    location /redirect_me {
        return 301 https://youtu.be/dQw4w9WgXcQ;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
        return 404 "Ceci n'est pas une page";
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires max;
        log_not_found off;
    }
}' > /etc/nginx/sites-available/custom

# Create a symbolic link to enable the custom configuration
ln -s /etc/nginx/sites-available/custom /etc/nginx/sites-enabled/

# Remove the default Nginx configuration
rm -f /etc/nginx/sites-enabled/default

# Create the custom 404 HTML page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Test Nginx configuration and reload Nginx
nginx -t && nginx -s reload
