#!/usr/bin/env bash
# Script to set up a new server with a custom 404 page in Nginx

# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx to use a custom 404 page
echo "error_page 404 /404.html;" >> /etc/nginx/sites-available/default

# Create the custom 404 page
echo "<html><body>Ceci n'est pas une page</body></html>" > /var/www/html/404.html

# Restart Nginx
/etc/init.d/nginx restart
