#!/usr/bin/env bash
# This script displays a list of currently running processes.

# Get a list of all processes and their hierarchy using the `ps` command.
process_list=$(ps axo pid,ppid,user,%cpu,%mem,vsz,rss,tty,stat,start,time,comm --forest)

# Display the process list in a user-friendly format.
echo "$process_list"
