#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process.

# Find the PID of the 4-to_infinity_and_beyond process
process_pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -z "$process_pid" ]; then
  echo "The 4-to_infinity_and_beyond process is not running."
else
  # Terminate the process using the kill command
  kill "$process_pid"
fi
