#!/usr/bin/env bash
# This script displays "To infinity and beyond" with a sleep of 2 in between.
# It handles the SIGTERM signal to display "I am invincible!!!" before terminating.

function handle_sigterm() {
    echo "I am invincible!!!"
}

trap 'handle_sigterm' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
