#!/usr/bin/env bash
# Displays all active IPv4 addresses on the machine.

# Get a list of all active IPv4 addresses assigned to network interfaces
ip_list=$(ip -4 addr | grep inet | awk '{print $2}' | cut -d '/' -f 1)

# Loop through the list and display each IP address
for ip in $ip_list; do
    echo "$ip"
done
